import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { ThemeProviders } from "./components/theme-providers"
import Header from './components/header'
import Footer from './components/footer'

// const pretendard = localFont({
//   src: '../public/PretendardVariable.woff2',
//   display: 'swap',
// })

export const metadata: Metadata = {
  title: 'Next13 Blog Starter',
  description: 'Generated by Nova',
  openGraph: {
    title: 'Next13 Blog Starter',
    description: 'Generated by Nova',
    url: 'https://next13-blog-starter-psi.vercel.app',
    siteName: 'Next13 Blog Starter',
    images: [
      {
        url: 'https://next13-blog-starter-psi.vercel.app/thumbnail.png',
        width: 800,
        height: 600,
      },
    ],
    locale: 'ko_KR',
    type: 'website',
  },  
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={`selection:bg-orange-400 selection:text-black dark:selection:text-white`}>
        <ThemeProviders>
          <Header />
            {children}
          <Footer />
        </ThemeProviders>
      </body>
    </html>
  )
}
